### ISSUE TITLE
burned_fuel coloumn must include a unit

### ISSUE THREAD

**Issue by flymia** [YAAMSOrg/yaams-sever#8]
It can happen, that many different airlines around the world use a YAAMS instance. If a U.S. based VA is using YAAMS, we need to make sure they can use the burned_fuel coloumn with a measurement unit. Maybe store this in the airlines table? (using KG or LBS)

**Comment by Konrad00** [comment]
I would prefer this to store it as an option for the whole airline. This gives us the possibility to use this information also on other fields in the data model, e.g. for weights of an aircraft in the future.
